version: '3.8'

services:
    gateway:
        build: ./ApiGatewayMicroservice
        # image:
        environment:
            BOOKS_SERVICE_API_ROUTE: books-service/api
            NODE_ENV: development
        ports:
            - 5000:80
        networks:
            # - net
            - gateway-books

    books-service:
        build: ./BooksMicroservice
        # image:
        environment:
            IO_SERVICE_API_ROUTE: io-service/api
            NODE_ENV: development
        networks:
            # - net
            - gateway-books
            - books-io

    io-service:
        build: ./IOMicroservice
        environment:
            PGUSER: admin
            PGPASSWORD: admin
            PGHOST: db
            PGPORT: 5432
            PGDATABASE: books
            NODE_ENV: development
        networks:
            - books-io
            - io-db

    db:
        image: postgres:12
        environment:
            POSTGRES_DB: books
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - database-vol:/var/lib/postgresql/data
            - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        networks:
            - io-db
            - db-adminer

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - db-adminer

volumes:
    database-vol:

networks:
    gateway-books:
    books-io:
    io-db:
    db-adminer:
